### ISSUE TITLE
可以换回以前那个有李白《长歌行》背景的界面吗？

### ISSUE THREAD

**Issue by Leslie-Wong-H** [michaelliao/shici#1]
廖老师，可以换回以前那个有李白《长歌行》背景的界面吗？
新界面实在很让人扫兴，少了很多诗意。
而且下面的footer弄得这么鲜明GitHub属性。
弄得好像每一个点进来的都是开发者一样，为这个仓库导流。。。
点开这个页面，就是想欣赏一下纯粹的诗歌而已。
新界面貌似丢了这个初心。

**Comment by michaelliao** [comment]
那是李白的《蜀道难》

**Comment by michaelliao** [comment]
![62d8efadjw1ecbwr0spm3j20jg0rsadj](https://user-images.githubusercontent.com/470058/49059939-45f33780-f246-11e8-8e58-e09382844108.jpg)
