### ISSUE TITLE
每日一诗API

### ISSUE THREAD

**Issue by ysctest** [michaelliao/shici#10]
廖老师，我看项目中有说提供api，能发下大致的api文档么，主要用来获取每日一诗

**Comment by yansheng836** [comment]
额，这里虽然提供了API，但是好像没有实现“每日一诗”这个API，提供的都是需要指定id的，详见：<https://github.com/michaelliao/shici/blob/master/web/src/main/java/com/itranswarp/shici/web/ApiController.java>。
可以自己实现一下，可参考这个方法：	<https://github.com/michaelliao/shici/blob/625d6746e7b427b28e1b7f1dff4fba2a0a2e5cc3/web/src/main/java/com/itranswarp/shici/service/PoemService.java#L50> 。

或者直接使用另一个现成的API：https://www.jinrishici.com/ 。

**Comment by michaelliao** [comment]
https://github.com/michaelliao/shici/pull/11
